### ISSUE TITLE
How can I write the output to the host computer?

### ISSUE THREAD

**Issue by CristianRiccio** [c-omics/busco#1]
`docker run -it -v $PWD:$PWD comics/busco bash -c "cd $PWD ; run_BUSCO.py -i target.fa -o SAMPLE -l example -m genome -c 1 -sp fly"` will write the busco output to `run_SAMPLE` and once the container has finished running everything, it will erase the container and its output. How can I capture the output of busco on my host machine?

I am currently using `docker run --name bristol -it -v $PWD:/input comics/busco bash -c "cd $PWD ; run_BUSCO.py -i /input/input/celegans.fa -o SAMPLE -l /input/input/nematoda_odb9 -m genome -c 1" > busco.bristol` with `celegans.fa` and `nematoda_odb0` in my input folder. This command does not write the busco analysis to my host machine. If I try to append `/input/` in front of `SAMPLE` to get the output on my host machine, it complains because busco does not want a path for the `-o` option: 

```
bash: line 0: cd: /Users/.../code: No such file or directory
ERROR   Please do not provide a full path in --out parameter, no slash. Use out_path in the config.ini file to specify the full path.
```
Can you help me, please? I would like to use your container to analyse some genome assemblies. I am working on macOS X. Note that `busco.bristol` does contain some output, such as C[D],F,M,n numbers because that's output for the standard output so I can redirect it to my host machine. However, I would like the tblastn, augustus, hmmer analyses as well.

Cheers.

**Comment by sglim2** [comment]
Hi,

Most of my testing is done under CentOS linux. Docker on MacOS works slightly differently than on Linux. Docker for Mac runs a virtual machine hidden from the users, but it makes it more difficult to do simple  bind-mounting with the docker -v flag.

But if you take a look at the 'File Sharing' tab in Docker Preferences you will see a list of folders that can be bind-mounted with the docker -v option.

So I have tried the command:

`docker run -it -v /Users:/Users comics/busco bash -c "cd $PWD ; run_BUSCO.py -i target.fa -o SAMPLE -l example -m genome -c 1 -sp fly"`

This seems to work. The difference to my original example is I'm mounting one of the supported folders, but I'm still using pwd to get to correct folder within the container. Of course, this does open up all of the /Users folder within the container. You may want to restrict this by changing the allowed bind-mount folders in the Docker preferences.

**Comment by sglim2** [comment]
closing issue
